### Задание № 1:
Датасет для домашнего задания находится в материалах занятия - файлы для домашнего задания «Библиотека Pandas».

Определите, какому фильму было выставлено больше всего оценок 5.0.

In [1]:
import pandas as pd

In [2]:
# открываем csv-шник, выводим шапку на экран
data_rating = pd.read_csv('ratings.csv')
data_rating.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [3]:
# выводим оценки строго= 5
ratings_5 = data_rating[data_rating['rating'] == 5]
ratings_5.head()

   userId  movieId  rating  timestamp
3       1       47     5.0  964983815
4       1       50     5.0  964982931
6       1      101     5.0  964980868
8       1      151     5.0  964984041
9       1      157     5.0  964984100

In [16]:
# value_counts подсчитываем количество значений по колонке фильмid
hg_rating = ratings_5['movieId'].value_counts()

# hg_rating.head() # вывод шапки в первых 5 фильмов для наглядности --топ 5

hg_rating  # вывод одного фильма топ 1

movieId
318       153
296       123
356       116
2571      109
260       104
         ...
107771      1
109968      1
115727      1
138632      1
156371      1
Name: count, Length: 2954, dtype: int64

In [27]:
print(f' Фильм, к-ому было выставлено больше всех 5.0 оценок \n movieId: {hg_rating.index[0]}, values: {hg_rating.values[0]}')

 Фильм, к-ому было выставлено больше всех 5.0 оценок
 movieId: 318, values: 153

In [24]:
hg_rating.values[0]

np.int64(153)

### Задание № 2:
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 год. Не учитывайте в расчётах отрицательные значения quantity.

In [5]:
data_power = pd.read_csv(
    r'C:\Users\fokin\Desktop\Перекатываемся\Нетология\Python\Вебинары\Pandas и numpy\power.csv'
)
data_power.head()

   country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [6]:
# просто чтобы посмотреть есть ли в списке искомые страны Латвия — Latvia / Литва — Lithuania / Эстония — Estonia
data_power[data_power['country'].str.contains('ia', case=False)]['country'].unique()

<StringArray>
[                    'Austria',                     'Czechia',
                     'Romania',                      'Serbia',
                    'Slovakia',                    'Bulgaria',
                     'Croatia',                   'Lithuania',
                  'Other Asia',      'T.F.Yug.Rep. Macedonia',
                    'Colombia',                   'Australia',
                    'Ethiopia',       'Serbia and Montenegro',
                     'Tunisia',                     'Georgia',
                      'Latvia',                     'Armenia',
          'Russian Federation',    'Bolivia (Plur. State of)',
                     'Estonia',     'Ethiopia, incl. Eritrea',
               'French Guiana',                   'Indonesia',
                     'Liberia',                    'Malaysia',
                  'Mauritania',                     'Namibia',
               'New Caledonia',                    'Slovenia',
     'United Rep. of Tanzania',    'Yugoslavia, SFR (former)',
                      'Zambia',                     'Algeria',
            'French Polynesia',        'Syrian Arab Republic',
                       'India',                     'Nigeria',
                     'Somalia',                     'Albania',
      'Bosnia and Herzegovina',     'Czechoslovakia (former)',
           'Equatorial Guinea',                'Saudi Arabia',
                   'St. Lucia',                    'Mongolia',
                    'Cambodia',                      'Gambia',
 'Micronesia (Fed. States of)',    'Northern Mariana Islands']
Length: 50, dtype: str

In [7]:
filter_country = data_power[
    (data_power['country'] == 'Latvia') | (data_power['country'] == 'Lithuania') | (
            data_power['country'] == 'Estonia')]

filter_country

           country  year  quantity  category
373      Lithuania  2014      39.0         1
374      Lithuania  2013     192.0         1
375      Lithuania  2012     196.0         1
376      Lithuania  2011     171.0         1
377      Lithuania  2010     158.0         1
...            ...   ...       ...       ...
1188862  Lithuania  2003       0.0        71
1188863  Lithuania  2002       0.0        71
1188864  Lithuania  2001       0.0        71
1188865  Lithuania  2000       0.0        71
1188866  Lithuania  1999       0.0        71

[27306 rows x 4 columns]

In [8]:
# после выполнения задумался об оптимизации, чтобы не писать грамоздкую конструкцию, если стран будет 25, 30,
# такое условие просто не написать, ИИ-шка подсказала использовать метод .isin() на всякий случай закомментрировал этот метод
# filter_country = data_power[data_power['country'].isin(['Latvia', 'Lithuania', 'Estonia'])]
# filter_country

In [9]:
filter_category = filter_country[
    (filter_country['category'] == 4) | (filter_country['category'] == 12) | (
            filter_country['category'] == 21)]

filter_category

          country  year  quantity  category
10617     Estonia  2008       1.0         4
10618     Estonia  2007       0.0         4
10619     Estonia  2006       0.0         4
10620     Estonia  2005       1.0         4
10621     Estonia  2004       1.0         4
...           ...   ...       ...       ...
253986  Lithuania  2005       1.0        21
253987  Lithuania  2004       1.0        21
253988  Lithuania  2003       0.0        21
253989  Lithuania  2002       0.0        21
253990  Lithuania  2001       0.0        21

[1253 rows x 4 columns]

In [10]:
# filter_category = filter_country[filter_country['category'].isin([4, 12, 21])]

# filter_category

In [11]:
filter_ccy = filter_category[
    (filter_category['year'] >= 2005) & (filter_category['year'] <= 2010) & (
                filter_category['quantity'] >= 0)]
filter_ccy

          country  year  quantity  category
10617     Estonia  2008       1.0         4
10618     Estonia  2007       0.0         4
10619     Estonia  2006       0.0         4
10620     Estonia  2005       1.0         4
11156   Lithuania  2008       1.0         4
...           ...   ...       ...       ...
253982  Lithuania  2009      98.0        21
253983  Lithuania  2008      54.0        21
253984  Lithuania  2007      47.0        21
253985  Lithuania  2006      31.0        21
253986  Lithuania  2005       1.0        21

[408 rows x 4 columns]

#### также подсмотрел пару способов для другого стиля записи:

In [12]:
# № 1:
# filter_ccy = filter_category[
#     filter_category['year'].between(2005, 2010) &
#     (filter_category['quantity'] >= 0)
#     ]

In [13]:
# № 2:
# filter_ccy = filter_category.query('2005 <= year <= 2010 and quantity >= 0')

In [14]:
total_sum_energy = filter_ccy['quantity'].sum()
# total_sum_energy

print(total_sum_energy)

240580.0

### Задание № 3:

Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas DataFrame. Вы можете взять любые страницы.
Примеры страниц:

https://fortrader.org/quotes;
pythonworld.ru...strok.html

попытка подклюиться к киберпанк вики)))

In [15]:
# я хотел из других сайтов взять данные по данным, но не получилось.
# наверное там какая-то блокировка от загрузки инфы не от пользователей

url = 'https://cyberpunk.fandom.com/ru/wiki/(Cyberpunk_2077)'

cyber_tables = pd.read_html(url)
cyber_tables

cyber_tables.info()

HTTPError: HTTP Error 403: Forbidden

в итоге взял из предложенных примеров в ДЗ

In [ ]:
url = 'https://pythonworld.ru/tipy-dannyx-v-python/stroki-funkcii-i-metody-strok.html'

pep_tables = pd.read_html(url)[0]
pep_tables

pep_tables.info()