### Задание № 1:
Напишите функцию, которая классифицирует фильмы из материалов занятия по правилам:

оценка 2 и ниже — низкий рейтинг;
оценка 4 и ниже — средний рейтинг;
оценка 4.5 и 5 — высокий рейтинг.

Результат классификации запишите в столбец class.

In [101]:
import pandas as pd

In [102]:
df = pd.read_csv('ratings.csv')

df.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [103]:
df_test = pd.DataFrame(
    {
        'user_id': [2, 15, 25, 35],
        'movieId': [33, 163, 130, 97],
        'rating': [4.7, 2, 4.3, 3.5],
        'timestamp': [964982703, 964981247, 964982703, 964981247]
    }
)
df_test.head()

   user_id  movieId  rating  timestamp
0        2       33     4.7  964982703
1       15      163     2.0  964981247
2       25      130     4.3  964982703
3       35       97     3.5  964981247

In [104]:
def classify_rang(row):
    '''
    классифицирует фильмы по рейтингу, где grade - это оценка:
    оценка (grade <= 2) 2 и ниже — низкий рейтинг;
    оценка (2 < grade <= 4) 4 и ниже — средний рейтинг;
    оценка (4.5 <= grade <= 5) 4.5 и 5 — высокий рейтинг (предположил что 4.5 и 5 -- диапазон).
    '''

    rating = row['rating']
    if rating <= 2:
        return 'низкий рейтинг'
    elif 2 < rating <= 4:
        return 'средний рейтинг'
    elif 4.5 <= rating <= 5:
        return 'высокий рейтинг'
    # внес на будущее, тк значения более 4 и менее 4.5 вне диапазона классификации
    # else:
    #     return 'вне классификации'

In [105]:
# РАДИ ЭКСПЕРИМЕНТА -> однострочник, знаю не читабельно итд(>_<)
df_test['class'] = df_test.apply(lambda row: 'низкий рейтинг' if row['rating'] <= 2 else 'средний рейтинг' if 2 < row['rating'] <= 4 else 'высокий рейтинг' if 4.5 <= row['rating'] <= 5 else None, axis=1)
df_test

   user_id  movieId  rating  timestamp            class
0        2       33     4.7  964982703  высокий рейтинг
1       15      163     2.0  964981247   низкий рейтинг
2       25      130     4.3  964982703              NaN
3       35       97     3.5  964981247  средний рейтинг

In [106]:
# проверяем на тестовом датасете:
df_test['class'] = df_test.apply(classify_rang, axis=1)
df_test

# вроде работает, выдал не классифицируемый рейтинг и другие рейтинги

   user_id  movieId  rating  timestamp            class
0        2       33     4.7  964982703  высокий рейтинг
1       15      163     2.0  964981247   низкий рейтинг
2       25      130     4.3  964982703              NaN
3       35       97     3.5  964981247  средний рейтинг

In [107]:
# применяем ф-цию к датафрейму по строкам по строкам целиком
df['class'] = df.apply(classify_rang, axis=1)
df

        userId  movieId  rating   timestamp            class
0            1        1     4.0   964982703  средний рейтинг
1            1        3     4.0   964981247  средний рейтинг
2            1        6     4.0   964982224  средний рейтинг
3            1       47     5.0   964983815  высокий рейтинг
4            1       50     5.0   964982931  высокий рейтинг
...        ...      ...     ...         ...              ...
100831     610   166534     4.0  1493848402  средний рейтинг
100832     610   168248     5.0  1493850091  высокий рейтинг
100833     610   168250     5.0  1494273047  высокий рейтинг
100834     610   168252     5.0  1493846352  высокий рейтинг
100835     610   170875     3.0  1493846415  средний рейтинг

[100836 rows x 5 columns]

### Задание № 2:

Используйте файл keywords.csv.

Нужно написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определённому региону. Т. е. если поисковый запрос содержит название города региона, то в столбце ‘region’ пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим ‘undefined’.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

Результат классификации запишите в отдельный столбец region.

In [108]:
geo_data = {
    'Центр': ['москва', 'тула', 'ярославль'],
    'Северо-Запад': ['петербург', 'псков', 'мурманск'],
    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

In [109]:
df_key = pd.read_csv('keywords.csv')
df_key.head()

         keyword     shows
0             вк  64292779
1  одноклассники  63810309
2          порно  41747114
3           ютуб  39995567
4      вконтакте  21014195

In [110]:
def geo_classify(row):
    '''
    ф-ция выставляет географическую принадлежность к определенному региону из geo_data

    Примечание:
    ф-ция достатолчно простая и не распознает падежи и склонения
    '''

    # контейнер для ячейки, также отбросил разницу в регистрах
    geo_class = row['keyword'].lower()

    # пробегаемся по словарю geo_data и достаем из него каждое название города (влож цикл)
    for region, cities in geo_data.items():
        for city in cities:
            if city in geo_class:
                return region

    return 'undefined'

In [111]:
df_test2 = pd.DataFrame(
    {
        'keyword': ['билеты в Москва', 'ютуб', 'Сахалин купить авто из Японии', 'билеты в Москву'],
        'show': [35, 66666, 22222, 11]
    }
)

In [112]:
df_test2['region'] = df_test2.apply(geo_classify, axis=1)
df_test2

                         keyword   show          region
0                билеты в Москва     35           Центр
1                           ютуб  66666       undefined
2  Сахалин купить авто из Японии  22222  Дальний Восток
3                билеты в Москву     11       undefined

На тестовых данных вроде все неплохо, строки из дата фрейма проходят проверку на соответствия городам из словаря.
#### НО!
не учитываются склонения, падежы, опечатки и сокращения => большой кусок данных у нас проходит мимо и классифицируется некорректно!

In [113]:
# Результат выполнения ф-ции
df_key['region'] = df_key.apply(geo_classify, axis=1)
df_key

                       keyword     shows     region
0                           вк  64292779  undefined
1                одноклассники  63810309  undefined
2                        порно  41747114  undefined
3                         ютуб  39995567  undefined
4                    вконтакте  21014195  undefined
...                        ...       ...        ...
99995   эльдорадо старый оскол      3705  undefined
99996      frigate для firefox      3630  undefined
99997                   укрсиб      3630  undefined
99998  погода в ялте на неделю      3688  undefined
99999                     ггму      3630  undefined

[100000 rows x 3 columns]

просто для наглядность проверял

In [114]:
# df_key.loc[3680:3725]

In [115]:
# df_key['region'].sort_values().unique()

In [116]:
# проверка есть ли что-то кроме 'undefined'
df_key[df_key['region'] != 'undefined']

                                     keyword   shows          region
127                             авито москва  979292           Центр
370                 авито ру санкт петербург  425134    Северо-Запад
564                погода в санкт петербурге  292489    Северо-Запад
849                          авито ярославль  209581           Центр
1063                     фарпост владивосток  176951  Дальний Восток
...                                      ...     ...             ...
99590  авито ярославль автомобили с пробегом    3673           Центр
99634   северпост новости мурманской области    3606    Северо-Запад
99808      полармед мурманск запись на прием    3719    Северо-Запад
99890                    яндекс метро москва    4548           Центр
99922                      авто ру ярославль    3712           Центр

[747 rows x 3 columns]

### Задание № 3:
Есть мнение, что раньше снимали настоящее кино, не то что сейчас.

Ваша задача — проверить это утверждение, используя файлы с рейтингами фильмов из прошлого домашнего занятия:
файл movies.csv и ratings.csv из базы.
Нужно проверить, верно ли, что с ростом года выпуска фильма его средний рейтинг становится ниже.

Вы не будете затрагивать субьективные факторы выставления этих рейтингов, а пройдётесь по алгоритму:

1. В переменную years запишите список из всех годов с 1950 по 2010 года.

2. Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска. Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте алгоритм:

- для каждой строки пройдите по всем годам списка years;
- если номер года присутствует в названии фильма, то функция возвращает этот год, как год выпуска;
- если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год.
3. Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец ‘year’.

4. Посчитайте средний рейтинг всех фильмов для каждого значения столбца ‘year’ и отсортируйте результат по убыванию рейтинга.

In [117]:
years_list = list(range(1950,2011))
years_list

[1950,
 1951,
 1952,
 1953,
 1954,
 1955,
 1956,
 1957,
 1958,
 1959,
 1960,
 1961,
 1962,
 1963,
 1964,
 1965,
 1966,
 1967,
 1968,
 1969,
 1970,
 1971,
 1972,
 1973,
 1974,
 1975,
 1976,
 1977,
 1978,
 1979,
 1980,
 1981,
 1982,
 1983,
 1984,
 1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010]

In [118]:
df_movies = pd.read_csv('movies.csv')
df_movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [119]:
df_ratings = pd.read_csv('ratings.csv')
df_ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [121]:
def production_year(row):
    '''
    ф-ция, которая каждой строке из названия фильма выставляет год выпуска 1/0
    '''

    str_year_release = row['title']

    for year in years_list:
        if '(' + str(year) + ')' in str_year_release:
            return year

    return 1900

In [122]:
df_movies['year'] = df_movies.apply(production_year, axis=1)
df_movies

,movieId,title,genres,year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men (1995),Comedy|Romance,1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II (1995),Comedy,1995
...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,1900
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,1900
9739,193585,Flint (2017),Drama,1900
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,1900
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,1991

In [123]:
joined_tables = df_ratings.merge(df_movies, on='movieId')
joined_tables

,userId,movieId,rating,timestamp,title,genres,year
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance,1995
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller,1995
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1995
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1995
...,...,...,...,...,...,...,...
100831,610,166534,4.0,1493848402,Split (2017),Drama|Horror|Thriller,1900
100832,610,168248,5.0,1493850091,John Wick: Chapter Two (2017),Action|Crime|Thriller,1900
100833,610,168250,5.0,1494273047,Get Out (2017),Horror,1900
100834,610,168252,5.0,1493846352,Logan (2017),Action|Sci-Fi,1900
100835,610,170875,3.0,1493846415,The Fate of the Furious (2017),Action|Crime|Drama|Thriller,1900

In [124]:
# сортировка по убыванию рейтинга и высчитывание среднего значения по 'rating'
# joined_tables.sort_values('rating', ascending=False) # шаблон как пишется сортировка в отдельную строку

joined_tables.groupby('year')[['rating']].mean().sort_values('rating', ascending=False)

        rating
year
1957  4.039535
1954  4.009191
1962  3.969466
1952  3.953125
1964  3.940160
...        ...
2000  3.398899
2005  3.359888
1992  3.354943
1997  3.347241
1996  3.335329

[62 rows x 1 columns]

## Итог:

в 50-х и 60-х годах средний балл рейтинга выше, чем в более позднее время.

### Однако

Возможно раньше снимали фильмы гораздо лучше.
НО что если в современности большее число респондентов проходят опросы и ставит оценки кино, нежели было в более ранние года и из-за этого такое утверждение не совсем корректное?

In [125]:
# joined_tables.groupby('year')[['rating']].count().sort_index()