### Задание № 1:
Для датафрейма log из материалов занятия создайте столбец source_type по правилам:

если источник traffic_source равен Yandex или Google, то в source_type ставится organic;
для источников paid и email из России ставим ad;
для источников paid и email не из России ставим other;
все остальные варианты берём из traffic_source без изменений.

In [28]:
import pandas as pd

In [29]:
df_log = pd.read_csv(r'C:\Users\fokin\Desktop\Перекатываемся\Netologia\Python\webinar\Pandas и numpy\ml-latest-small\visit_log.csv', sep=';')
df_log

,timestamp,visit_id,url,region,user_id,traffic_source
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex
...,...,...,...,...,...,...
18933,1550094288,57e5ba8560,https://host.ru/c2382eb3d6afc8d0f3,Belarus,98b19810d0,paid
18934,1550094296,6f9389ec1b,https://host.ru/f1eb4601740d627ab0,Russia,32ebb20c13,paid
18935,1550094308,e8cf2eb8e6,https://host.ru/a5dda93e70318570c0,Belarus,b85baa8c73,yandex
18936,1550094314,79530b9a67,https://host.ru/6fda01ec57f23abc9e,Russia,e154b06121,paid
18937,1550094323,b3b634f824,https://host.ru/39fa884393666d45fc,Russia,7d27a58fb8,email

In [30]:
def get_source_type(row):
    source_type = row['traffic_source'].lower()
    if (source_type == 'yandex') | (source_type == 'google'):
        source_type = 'organic'
    elif ((source_type == 'paid') | (source_type == 'email')) & (row['region'] == 'Russia'):
        source_type = 'ad'
    elif ((source_type == 'paid') | (source_type == 'email')) & (row['region'] != 'Russia'):
        source_type = 'other'
    else:
        source_type = row['traffic_source']

    return source_type

In [31]:
df_log['source_type'] = df_log.apply(get_source_type, axis=1)
df_log.head(12)

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,organic
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,organic
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,organic
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,organic
5,1549980742,8855508aad,https://host.ru/df646c3676cc259fa0,Russia,fc43898e47,yandex,organic
6,1549980742,b0f66adc83,https://host.ru/b8b58337d272ee7b15,Russia,13fc55e781,paid,ad
7,1549980754,837885c8f8,https://host.ru/108ce4b365afb7b88e,Russia,cb5082b6f6,direct,direct
8,1549980760,af5570f5a1,https://host.ru/3004a8273caeef2867,China,45664f7af2,direct,direct
9,1549980765,3e7077fd2f,https://host.ru/df646c3676cc259fa0,Russia,6f9de8c8b6,email,ad
10,1549980777,01d448afd9,https://host.ru/a5dda93e70318570c0,India,27e76a4a80,direct,direct
11,1549980785,71b6c1d538,https://host.ru/c8d9213a31839f9a3a,Ukraine,3b13701488,google,organic

### Задание № 2:
В файле URLs.txt содержатся URL страниц новостного сайта. Вам нужно отфильтровать его по адресам страниц с текстами новостей. Известно, что шаблон страницы новостей имеет внутри URL конструкцию: /, затем 8 цифр, затем дефис. Выполните действия:

- Прочитайте содержимое файла с датафрейм.
- Отфильтруйте страницы с текстом новостей, используя метод str.contains и регулярное выражение в соответствие с заданным шаблоном.

In [32]:
from urllib import parse

In [33]:
df_url_txt = pd.read_csv(r'C:\Users\fokin\Desktop\Перекатываемся\Netologia\Python\webinar\Pandas и numpy\ml-latest-small\URLs.txt', header=None)
df_url_txt

                                                    0
0                                                 url
1                                             /world/
2                                            /latest/
3                                       /?updated=top
4   /politics/36188461-s-marta-zhizn-rossiyan-susc...
..                                                ...
89  /cis/35984145-kreml-prokommentiroval-soobschen...
90  /video/36071019-olimpiyskie-obekty-rio-prevrat...
91  /science/36151301-nazvano-posledstvie-zloupotr...
92  /incidents/36027330-vospitatelnitsu-zatravili-...
93  /world/36103095-dominikanskih-zhurnalistov-ubi...

[94 rows x 1 columns]

In [34]:
df_url_txt[0].str.contains(r'/\d{8}-')

0     False
1     False
2     False
3     False
4      True
      ...
89     True
90     True
91     True
92     True
93     True
Name: 0, Length: 94, dtype: bool

In [35]:
search_link = df_url_txt[ df_url_txt[0].str.contains(r'/\d{8}-') ]
search_link

                                                    0
4   /politics/36188461-s-marta-zhizn-rossiyan-susc...
5   /world/36007585-tramp-pridumal-kak-reshit-ukra...
6   /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
7   /video/36001498-poyavilis-pervye-podrobnosti-g...
8   /world/36007585-tramp-pridumal-kak-reshit-ukra...
..                                                ...
89  /cis/35984145-kreml-prokommentiroval-soobschen...
90  /video/36071019-olimpiyskie-obekty-rio-prevrat...
91  /science/36151301-nazvano-posledstvie-zloupotr...
92  /incidents/36027330-vospitatelnitsu-zatravili-...
93  /world/36103095-dominikanskih-zhurnalistov-ubi...

[84 rows x 1 columns]

### Задание № 3:
Используйте файл с оценками фильмов ml-latest-small/ratings.csv. Посчитайте среднее время жизни пользователей, которые выставили более 100 оценок. Под временем жизни понимается разница между максимальным и минимальным значениями столбца timestamp для данного значения userId.

In [36]:
df_ratings = pd.read_csv(r'C:\Users\fokin\Desktop\Перекатываемся\Netologia\Python\webinar\Pandas и numpy\ml-latest-small\ratings.csv')
df_ratings

        userId  movieId  rating   timestamp
0            1       31     2.5  1260759144
1            1     1029     3.0  1260759179
2            1     1061     3.0  1260759182
3            1     1129     2.0  1260759185
4            1     1172     4.0  1260759205
...        ...      ...     ...         ...
99999      671     6268     2.5  1065579370
100000     671     6269     4.0  1065149201
100001     671     6365     4.0  1070940363
100002     671     6385     2.5  1070979663
100003     671     6565     3.5  1074784724

[100004 rows x 4 columns]

In [37]:
# rating_count = df_ratings.groupby('userId')[['rating']].count().sort_values(['rating'], ascending=False)
# rating_count = df_ratings.groupby('userId')[['rating']].count()
# rating_count # 671 строка

In [38]:
# rating_count100 = rating_count[rating_count['rating'] > 100]
# rating_count100 # 258 строк

думал идти поэтапно, но по итогу решил не джоинить столбцы и решил через agg

In [39]:
rating_count = df_ratings.groupby('userId').agg({
    'rating': 'count',
    'timestamp': lambda x: x.max() - x.min()
})
rating_count

        rating  timestamp
userId
1           20         97
2           76        851
3           51      71198
4          204     203560
5          100       2101
...        ...        ...
667         68       1014
668         20        282
669         37        685
670         31    2162705
671        115   11283984

[671 rows x 2 columns]

In [40]:
rating_higher_100 = rating_count[rating_count['rating'] > 100]
rating_higher_100

        rating  timestamp
userId
4          204     203560
8          116      85187
15        1700  471393496
17         363       8053
19         423       5282
...        ...        ...
656        128       3053
659        142   31609411
664        519   98180439
665        434   54131471
671        115   11283984

[258 rows x 2 columns]

In [41]:
result_day = rating_higher_100['timestamp'].mean()
result_day

np.float64(40080507.4496124)

In [42]:
# или сразу расчет
# result = rating_higher_100 = rating_count[rating_count['rating'] > 100]['timestamp'].mean()

In [43]:
print(f'Среднее время жизни пользователя: {result_day / 86400:.2f} суток')

Среднее время жизни пользователя: 463.89 суток

### Задание № 4:
Дана статистика услуг перевозок клиентов компании по типам (см. файл “Python_13_join.ipynb” в разделе «Материалы для лекции “Продвинутый pandas”» ---- Ноутбуки к лекции «Продвинутый pandas»).
Нужно сформировать две таблицы:

- таблицу с тремя типами выручки для каждого client_id без указания адреса клиента;
- аналогичную таблицу по типам выручки с указанием адреса клиента.

Обратите внимание, что в процессе объединения таблиц данные не должны теряться.

In [44]:
rzd = pd.DataFrame(
    {
        'client_id': [111, 112, 113, 114, 115],
        'rzd_revenue': [1093, 2810, 10283, 5774, 981]
    }
)
rzd

   client_id  rzd_revenue
0        111         1093
1        112         2810
2        113        10283
3        114         5774
4        115          981

In [45]:
auto = pd.DataFrame(
    {
        'client_id': [113, 114, 115, 116, 117],
        'auto_revenue': [57483, 83, 912, 4834, 98]
    }
)
auto

   client_id  auto_revenue
0        113         57483
1        114            83
2        115           912
3        116          4834
4        117            98

In [46]:
air = pd.DataFrame(
    {
        'client_id': [115, 116, 117, 118],
        'air_revenue': [81, 4, 13, 173]
    }
)
air

   client_id  air_revenue
0        115           81
1        116            4
2        117           13
3        118          173

In [47]:
client_base = pd.DataFrame(
    {
        'client_id': [111, 112, 113, 114, 115, 116, 117, 118],
        'address': ['Комсомольская 4', 'Энтузиастов 8а', 'Левобережная 1а', 'Мира 14', 'ЗЖБИиДК 1',
                    'Строителей 18', 'Панфиловская 33', 'Мастеркова 4']
    }
)
client_base

   client_id          address
0        111  Комсомольская 4
1        112   Энтузиастов 8а
2        113  Левобережная 1а
3        114          Мира 14
4        115        ЗЖБИиДК 1
5        116    Строителей 18
6        117  Панфиловская 33
7        118     Мастеркова 4

In [ ]:
# можно по одной джоинить, но я сразу 3 таблицы состыковал

In [59]:
# df_revenues = rzd.merge(auto, how='outer', on='client_id')
# df_revenues

In [60]:
# df_revenues = df_revenues.merge(air, how='outer', on='client_id')
# df_revenues

In [61]:
# сперва соединяем rzd с auto через how='outer', чтобы не потерять все значения, аналогично соединяю air
df_revenues = rzd.merge(auto, how='outer', on='client_id').merge(air, how='outer', on='client_id')
df_revenues

   client_id  rzd_revenue  auto_revenue  air_revenue
0        111       1093.0           NaN          NaN
1        112       2810.0           NaN          NaN
2        113      10283.0       57483.0          NaN
3        114       5774.0          83.0          NaN
4        115        981.0         912.0         81.0
5        116          NaN        4834.0          4.0
6        117          NaN          98.0         13.0
7        118          NaN           NaN        173.0

In [63]:
# Если следовать логике чтобы ничего не потерялось, нужно соединять опять через 'outer', но в нашем случае у нас список клиентов все id охватывает, поэтому взял через'inner'
df_revenues_address = df_revenues.merge(client_base, how='inner', on='client_id')
df_revenues_address

   client_id  rzd_revenue  auto_revenue  air_revenue          address
0        111       1093.0           NaN          NaN  Комсомольская 4
1        112       2810.0           NaN          NaN   Энтузиастов 8а
2        113      10283.0       57483.0          NaN  Левобережная 1а
3        114       5774.0          83.0          NaN          Мира 14
4        115        981.0         912.0         81.0        ЗЖБИиДК 1
5        116          NaN        4834.0          4.0    Строителей 18
6        117          NaN          98.0         13.0  Панфиловская 33
7        118          NaN           NaN        173.0     Мастеркова 4